routes/web.php
    Route::get('/settings', 'SettingController@index')->name('settings.index');
    Route::get('gpa/create-gpa', 'GradesystemController@create');
    Route::post('create-gpa', 'GradesystemController@store');
    Route::post('gpa/delete', 'GradesystemController@destroy');
});

Route::middleware(['auth', 'teacher'])->group(function () {
    Route::get('gpa/all-gpa', 'GradesystemController@index');
});

Route::middleware(['auth'])->group(function () {
    if ('production' != config('app.env')) {
        Route::get('user/config/impersonate', 'UserController@impersonateGet');
        Route::post('user/config/impersonate', 'UserController@impersonate');
    }

    Route::get('users/{school_code}/{student_code}/{teacher_code}', 'UserController@index');
    Route::get('users/{school_code}/{role}', 'UserController@indexOther');
    Route::get('user/{user_code}', 'UserController@show');
    Route::get('user/config/change_password', 'UserController@changePasswordGet');
    Route::post('user/config/change_password', 'UserController@changePasswordPost');
    Route::get('section/students/{section_id}', 'UserController@sectionStudents');

    Route::get('courses/{teacher_id}/{section_id}', 'CourseController@index');
});

Route::middleware(['auth', 'teacher'])->group(function () {
    Route::get('course/students/{teacher_id}/{course_id}/{exam_id}/{section_id}', 'CourseController@course');
    Route::post('courses/create', 'CourseController@create');
    // Route::post('courses/save-under-exam', 'CourseController@update');
    Route::post('courses/store', 'CourseController@store');
    Route::post('courses/save-configuration', 'CourseController@saveConfiguration');
});

Route::middleware(['auth', 'admin'])->prefix('academic')->name('academic.')->group(function () {
    Route::get('syllabus', 'SyllabusController@index');
    Route::get('syllabus/{class_id}', 'SyllabusController@create');
    Route::get('notice', 'NoticeController@create');
    Route::get('event', 'EventController@create');
    Route::get('certificate', 'CertificateController@create');
    Route::get('routine', 'RoutineController@index');
    Route::get('routine/{section_id}', 'RoutineController@create');
    Route::prefix('remove')->name('remove.')->group(function () {
        Route::get('syllabus/{id}', 'SyllabusController@update');
        Route::get('notice/{id}', 'NoticeController@update');
        Route::get('event/{id}', 'EventController@update');
        Route::get('certificate/{id}', 'CertificateController@update');
        Route::get('routine/{id}', 'RoutineController@update');
    });
});

Route::middleware(['auth', 'student'])->group(function () {
    Route::get('user/{id}/notifications', 'NotificationController@index');
    Route::get('academic/student/certificates', 'CertificateController@index');
});

Route::middleware(['auth', 'admin'])->prefix('exams')->name('exams.')->group(function () {
    Route::get('/', 'ExamController@index');
    Route::get('create', 'ExamController@create');
    Route::post('create', 'ExamController@store');
    Route::post('activate-exam', 'ExamController@update');
});

Route::middleware(['auth', 'teacher'])->group(function () {
    Route::get('exams/active', 'ExamController@indexActive');
    Route::get('school/sections', 'SectionController@index');
});

Route::middleware(['auth', 'librarian'])->namespace('Library')->group(function () {
    Route::prefix('library')->name('library.')->group(function () {
        Route::resource('books', 'BookController');
    });
});

Route::middleware(['auth', 'librarian'])->prefix('library')->name('library.issued-books.')->group(function () {
    Route::get('issue-books', 'IssuedbookController@create')->name('create');
    Route::post('issue-books', 'IssuedbookController@store')->name('store');
    Route::get('issued-books', 'IssuedbookController@index')->name('index');
    Route::post('save_as_returned', 'IssuedbookController@update');
});

Route::middleware(['auth', 'accountant'])->prefix('accounts')->name('accounts.')->group(function () {
    Route::get('sectors', 'AccountController@sectors')->name('sectors.index');
    Route::post('create-sector', 'AccountController@storeSector')->name('sectors.create');
    Route::get('edit-sector/{sector}', 'AccountController@editSector')->name('sectors.edit');
    Route::patch('update-sector/{sector}', 'AccountController@updateSector')->name('sectors.update');
    //Route::get('delete-sector/{sector}','AccountController@deleteSector')->name('sectors.delete');

    Route::get('income', 'AccountController@income');
    Route::post('create-income', 'AccountController@storeIncome');
    Route::get('income-list', 'AccountController@listIncome');
    Route::post('list-income', 'AccountController@postIncome');
    Route::get('edit-income/{id}', 'AccountController@editIncome');
    Route::post('update-income', 'AccountController@updateIncome');
    Route::get('delete-income/{id}', 'AccountController@deleteIncome');

    Route::get('expense', 'AccountController@expense');
    Route::post('create-expense', 'AccountController@storeExpense');
    Route::get('expense-list', 'AccountController@listExpense');
    Route::post('list-expense', 'AccountController@postExpense');
    Route::get('edit-expense/{id}', 'AccountController@editExpense');
    Route::post('update-expense', 'AccountController@updateExpense');
    Route::get('delete-expense/{id}', 'AccountController@deleteExpense');
});

Route::middleware(['auth', 'master'])->group(function () {
    Route::get('register/admin/{id}/{code}', function ($id, $code) {
        session([
        'register_role' => 'admin',
        'register_school_id' => $id,
        'register_school_code' => $code,
        ]);

        return redirect()->route('register');
    });
    Route::post('register/admin', 'UserController@storeAdmin');
    Route::get('master/activate-admin/{id}', 'UserController@activateAdmin');
    Route::get('master/deactivate-admin/{id}', 'UserController@deactivateAdmin');
    Route::get('school/admin-list/{school_id}', 'SchoolController@show');
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::prefix('school')->name('school.')->group(function () {
        Route::post('add-class', 'MyclassController@store');
        Route::post('add-section', 'SectionController@store');
        Route::post('add-department', 'SchoolController@addDepartment');
        Route::get('promote-students/{section_id}', 'UserController@promoteSectionStudents');
        Route::post('promote-students', 'UserController@promoteSectionStudentsPost');
        Route::post('theme', 'SchoolController@changeTheme');
        Route::post('set-ignore-sessions', 'SchoolController@setIgnoreSessions');
    });

    Route::prefix('register')->name('register.')->group(function () {
        Route::get('student', 'UserController@redirectToRegisterStudent');
        Route::get('teacher', function () {
            $departments = \App\Department::where('school_id', \Auth::user()->school_id)->get();
            $classes = \App\Myclass::where('school_id', \Auth::user()->school->id)->pluck('id');
            $sections = \App\Section::with('class')->whereIn('class_id', $classes)->get();
            session([
        'register_role' => 'teacher',
        'departments' => $departments,
        'register_sections' => $sections,
      ]);

            return redirect()->route('register');
        });
        Route::get('accountant', function () {
            session(['register_role' => 'accountant']);

            return redirect()->route('register');
        });
        Route::get('librarian', function () {
            session(['register_role' => 'librarian']);

            return redirect()->route('register');
        });
        Route::post('student', 'UserController@store');
        Route::post('teacher', 'UserController@storeTeacher');
        Route::post('accountant', 'UserController@storeAccountant');
        Route::post('librarian', 'UserController@storeLibrarian');
    });
    Route::get('edit/course/{id}', 'CourseController@edit');
    Route::post('edit/course/{id}', 'CourseController@updateNameAndTime');
});

//use PDF;
Route::middleware(['auth', 'master.admin'])->group(function () {
    Route::get('edit/user/{id}', 'UserController@edit');
    Route::post('edit/user', 'UserController@update');
    Route::post('upload/file', 'UploadController@upload');
    Route::post('users/import/user-xlsx', 'UploadController@import');
    Route::get('users/export/students-xlsx', 'UploadController@export');
    //   Route::get('pdf/profile/{user_id}',function($user_id){
//     $data = App\User::find($user_id);
//     PDF::setOptions(['defaultFont' => 'sans-serif', 'isHtml5ParserEnabled' => true]);
//     $pdf = PDF::loadView('pdf.profile-pdf', ['user' => $data]);
// 		return $pdf->stream('profile.pdf');
//   });
//   Route::get('pdf/result/{user_id}/{exam_id}',function($user_id, $exam_id){
//     $data = App\User::find($user_id);
//     $grades = App\Grade::with('exam')->where('student_id', $user_id)->where('exam_id',$exam_id)->latest()->get();
//     PDF::setOptions(['defaultFont' => 'sans-serif', 'isHtml5ParserEnabled' => true]);
//     $pdf = PDF::loadView('pdf.result-pdf', ['grades' => $grades, 'user'=>$data]);
// 		return $pdf->stream('result.pdf');
//   });
});
Route::middleware(['auth', 'teacher'])->group(function () {
    Route::post('calculate-marks', 'GradeController@calculateMarks');
    Route::post('message/students', 'NotificationController@store');
});
// Route::middleware(['auth'])->group(function (){
//   Route::get('download/pdf', function(){
//     $pathToFile = public_path('storage/Bano-EducationandAspiration.pdf');
//     return response()->download($pathToFile);
//   });
// });

// View Emails - in browser
Route::prefix('emails')->group(function () {
    // Welcome Email
    Route::get('/welcome', function () {
        $user = App\User::find(1);
        $password = 'ABCXYZ';

app/Book.php
<?php

namespace App;

class Book extends Model
{
    protected $fillable = [
        'title', 'book_code', 'author', 'quantity', 'rackNo', 'rowNo', 'type',
        'about', 'price', 'img_path', 'class_id', 'school_id', 'user_id',
    ];

    public function school()
    {
        return $this->belongsTo('App\School');
    }

    public function class()
    {
        return $this->belongsTo('App\Myclass');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function issuedbook()
    {
        return $this->hasMany('App\Issuedbook', 'book_id');
    }
}

app/Http/Controllers/Library/BookController.php
<?php

namespace App\Http\Controllers\Library;

use App\Book;
use App\Myclass;
use App\Http\Controllers\Controller;
use App\Http\Requests\Library\BookRequest;

class BookController extends Controller
{
    public function __construct()
    {
        view()->share('types', [
           __('Academic'),
           __('Magazine'),
           __('Story'),
           __('Other'),
        ]);
    }

    public function index()
    {
        $books = Book::bySchool(auth()->user()->school_id)->paginate();

        return view('library.books.index', compact('books'));
    }

    public function show(Book $book)
    {
        return view('library.books.show', compact('book'));
    }

    public function edit(Book $book)
    {
        $classes = Myclass::bySchool(auth()->user()->school_id)->get();

        return view('library.books.edit', compact('book', 'classes'));
    }

    public function create()
    {
        $classes = Myclass::bySchool(auth()->user()->school_id)->get();

        return view('library.books.create', compact('classes'));
    }

    public function store(BookRequest $request)
    {
        $book = Book::create([
            'title' => $request->title,
            'book_code' => $request->book_code,
            'author' => $request->author,
            'quantity' => $request->quantity,
            'rackNo' => $request->rackNo,
            'rowNo' => $request->rowNo,
            'type' => $request->type,
            'about' => $request->about,
            'price' => $request->price,
            'img_path' => $request->img_path,
            'class_id' => $request->class_id,
            'school_id' => auth()->user()->school_id,
            'user_id' => auth()->user()->id,
        ]);

        return redirect()->route('library.books.show', $book->id);
    }

    public function update(BookRequest $request, $book)
    {
        Book::where('id', $book)->update($request->except('_method', '_token'));

        return redirect()->route('library.books.index')->with('status', __('Book has been updated correctly'));
    }
}

resources/views/library/books/create-form.blade.php
<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
    <label for="title" class="col-md-4 control-label">@lang('Book Title')</label>

    <div class="col-md-6">
        <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}" placeholder="@lang('Book Title')" required>

        @if ($errors->has('title'))
            <span class="help-block">
                <strong>{{ $errors->first('title') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('about') ? ' has-error' : '' }}">
    <label for="about" class="col-md-4 control-label">@lang('About Book')</label>

    <div class="col-md-6">
        <textarea rows="3" id="about" type="text" class="form-control" name="about" placeholder="@lang('About Book')" required>{{ old('about') }}</textarea>

        @if ($errors->has('about'))
            <span class="help-block">
                <strong>{{ $errors->first('about') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('book_code') ? ' has-error' : '' }}">
    <label for="book_code" class="col-md-4 control-label">@lang('Book Code')</label>

    <div class="col-md-6">
        <input id="book_code" type="text" class="form-control" name="book_code" value="{{ old('book_code') }}" placeholder="@lang('Book Code')" required>

        @if ($errors->has('book_code'))
            <span class="help-block">
                <strong>{{ $errors->first('book_code') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('author') ? ' has-error' : '' }}">
    <label for="author" class="col-md-4 control-label">@lang('Book Author')</label>

    <div class="col-md-6">
        <input id="author" type="text" class="form-control" name="author" value="{{ old('author') }}" placeholder="@lang('Book Author')" required>

        @if ($errors->has('author'))
            <span class="help-block">
                <strong>{{ $errors->first('author') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
    <label for="price" class="col-md-4 control-label">@lang('Book Price')</label>

    <div class="col-md-6">
        <input id="price" type="number" class="form-control" name="price" value="{{ old('price') }}" placeholder="@lang('Book Price')" required>

        @if ($errors->has('price'))
            <span class="help-block">
                <strong>{{ $errors->first('price') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('quantity') ? ' has-error' : '' }}">
    <label for="quantity" class="col-md-4 control-label">@lang('Book Quantity')</label>

    <div class="col-md-6">
        <input id="quantity" type="number" class="form-control" name="quantity" value="{{ old('quantity') }}" placeholder="@lang('Book Quantity')" required>

        @if ($errors->has('quantity'))
            <span class="help-block">
                <strong>{{ $errors->first('quantity') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('rackNo') ? ' has-error' : '' }}">
    <label for="rackNo" class="col-md-4 control-label">@lang('Book Rack Number')</label>

    <div class="col-md-6">
        <input id="rackNo" type="number" class="form-control" name="rackNo" value="{{ old('rackNo') }}" placeholder="@lang('Book Rack Number')" required>

        @if ($errors->has('rackNo'))
            <span class="help-block">
                <strong>{{ $errors->first('rackNo') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('rowNo') ? ' has-error' : '' }}">
    <label for="rowNo" class="col-md-4 control-label">@lang('Book Row Number')</label>

    <div class="col-md-6">
        <input id="rowNo" type="number" class="form-control" name="rowNo" value="{{ old('rowNo') }}" placeholder="@lang('Book Row Number')" required>

        @if ($errors->has('rowNo'))
            <span class="help-block">
                <strong>{{ $errors->first('rowNo') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('img_path') ? ' has-error' : '' }}">
    <label for="img_path" class="col-md-4 control-label">@lang('Book Image Url')</label>

    <div class="col-md-6">
        <input id="img_path" type="text" class="form-control" name="img_path" value="{{ old('img_path') }}" placeholder="@lang('Book Image Url')" required>

        @if ($errors->has('img_path'))
            <span class="help-block">
                <strong>{{ $errors->first('img_path') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
    <label for="type" class="col-md-4 control-label">@lang('Book Type')</label>

    <div class="col-md-6">
        <select id="type" class="form-control" name="type">
            @foreach( $types as $type )
                <option value="{{ $type }}" @if (isset($book)) {{ $book->type== $type ? 'Selected' : '' }} @endif >
                    {{ $type }}
                </option>
            @endforeach
        </select>

        @if ($errors->has('type'))
            <span class="help-block">
                <strong>{{ $errors->first('type') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('class_id') ? ' has-error' : '' }}">
    <label for="class_id" class="col-md-4 control-label">@lang('For Class')</label>

    <div class="col-md-6">
        <select id="class_id" class="form-control" name="class_id">
            @foreach($classes as $class)
                <option value="{{ $class->id }}" @if(isset($book)) {{ $book->class_id == $class->id ? 'Selected' : '' }} @endif>
                    {{ $class->class_number }} {{ $class->group }}
                </option>
            @endforeach
        </select>

        @if ($errors->has('class_id'))
            <span class="help-block">
                <strong>{{ $errors->first('class_id') }}</strong>
            </span>
        @endif
    </div>
</div>

resources/views/library/books/create.blade.php
@extends('layouts.app')

@section('title', __('Add New Book'))

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2" id="side-navbar">
                @include('layouts.leftside-menubar')
            </div>
            <div class="col-md-8" id="main-container">
                <div class="panel panel-default">
                    <div class="page-panel-title">@lang('Add New Book')</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('library.books.store') }}" method="POST" class="form-horizontal">
                            {{ csrf_field() }}
                            @include('library.books.create-form')

                            <div class="form-group">
                                <div class="col-sm-offset-4 col-sm-8">
                                    <button type="submit" class="btn btn-danger">@lang('Save')</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/library/books/edit.blade.php
@extends('layouts.app')

@section('title', __('Edit Book'))

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2" id="side-navbar">
                @include('layouts.leftside-menubar')
            </div>
            <div class="col-md-8" id="main-container">
                <div class="panel panel-default">
                    <div class="page-panel-title">@lang('Edit Book Info')</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ url('library/books', $book->id) }}" method="POST" class="form-horizontal">

                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            @include('library.books.form', $book)

                            <div class="form-group">
                                <div class="col-sm-offset-4 col-sm-8">
                                    <button type="submit" class="btn btn-danger">@lang('Update Book Info')</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/library/books/form.blade.php
<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
    <label for="title" class="col-md-4 control-label">@lang('Book Title')</label>

    <div class="col-md-6">
        <input id="title" type="text" class="form-control" name="title" value="{{ $book->title Or old('title') }}" placeholder="@lang('Book Title')" required>

        @if ($errors->has('title'))
            <span class="help-block">
                <strong>{{ $errors->first('title') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('about') ? ' has-error' : '' }}">
    <label for="about" class="col-md-4 control-label">@lang('About Book')</label>

    <div class="col-md-6">
        <textarea rows="3" id="about" type="text" class="form-control" name="about" placeholder="@lang('About Book')" required>{{ $book->about Or old('about') }}</textarea>

        @if ($errors->has('about'))
            <span class="help-block">
                <strong>{{ $errors->first('about') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('book_code') ? ' has-error' : '' }}">
    <label for="book_code" class="col-md-4 control-label">@lang('Book Code')</label>

    <div class="col-md-6">
        <input id="book_code" type="text" class="form-control" name="book_code" value="{{ $book->book_code Or old('book_code') }}" placeholder="@lang('Book Code')" required>

        @if ($errors->has('book_code'))
            <span class="help-block">
                <strong>{{ $errors->first('book_code') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('author') ? ' has-error' : '' }}">
    <label for="author" class="col-md-4 control-label">@lang('Book Author')</label>

    <div class="col-md-6">
        <input id="author" type="text" class="form-control" name="author" value="{{ $book->author Or old('author') }}" placeholder="@lang('Book Author')" required>

        @if ($errors->has('author'))
            <span class="help-block">
                <strong>{{ $errors->first('author') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
    <label for="price" class="col-md-4 control-label">@lang('Book Price')</label>

    <div class="col-md-6">
        <input id="price" type="number" class="form-control" name="price" value="{{ $book->price Or old('price') }}" placeholder="@lang('Book Price')" required>

        @if ($errors->has('price'))
            <span class="help-block">
                <strong>{{ $errors->first('price') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('quantity') ? ' has-error' : '' }}">
    <label for="quantity" class="col-md-4 control-label">@lang('Book Quantity')</label>

    <div class="col-md-6">
        <input id="quantity" type="number" class="form-control" name="quantity" value="{{ $book->quantity Or old('quantity') }}" placeholder="@lang('Book Quantity')" required>

        @if ($errors->has('quantity'))
            <span class="help-block">
                <strong>{{ $errors->first('quantity') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('rackNo') ? ' has-error' : '' }}">
    <label for="rackNo" class="col-md-4 control-label">@lang('Book Rack Number')</label>

    <div class="col-md-6">
        <input id="rackNo" type="number" class="form-control" name="rackNo" value="{{ $book->rackNo Or old('rackNo') }}" placeholder="@lang('Book Rack Number')" required>

        @if ($errors->has('rackNo'))
            <span class="help-block">
                <strong>{{ $errors->first('rackNo') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('rowNo') ? ' has-error' : '' }}">
    <label for="rowNo" class="col-md-4 control-label">@lang('Book Row Number')</label>

    <div class="col-md-6">
        <input id="rowNo" type="number" class="form-control" name="rowNo" value="{{ $book->rowNo Or old('rowNo') }}" placeholder="@lang('Book Row Number')" required>

        @if ($errors->has('rowNo'))
            <span class="help-block">
                <strong>{{ $errors->first('rowNo') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('img_path') ? ' has-error' : '' }}">
    <label for="img_path" class="col-md-4 control-label">@lang('Book Image Url')</label>

    <div class="col-md-6">
        <input id="img_path" type="text" class="form-control" name="img_path" value="{{ $book->img_path Or old('img_path') }}" placeholder="@lang('Book Image Url')" required>

        @if ($errors->has('img_path'))
            <span class="help-block">
                <strong>{{ $errors->first('img_path') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
    <label for="type" class="col-md-4 control-label">@lang('Book Type')</label>

    <div class="col-md-6">
        <select id="type" class="form-control" name="type">
            @foreach( $types as $type )
                <option value="{{ $type }}" @if (isset($book)) {{ $book->type== $type ? 'Selected' : '' }} @endif >
                    {{ $type }}
                </option>
            @endforeach
        </select>

        @if ($errors->has('type'))
            <span class="help-block">
                <strong>{{ $errors->first('type') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('class_id') ? ' has-error' : '' }}">
    <label for="class_id" class="col-md-4 control-label">@lang('For Class')</label>

    <div class="col-md-6">
        <select id="class_id" class="form-control" name="class_id">
            @foreach($classes as $class)
                <option value="{{ $class->id }}" @if(isset($book)) {{ $book->class_id == $class->id ? 'Selected' : '' }} @endif>
                    {{ $class->class_number }} {{ $class->group }}
                </option>
            @endforeach
        </select>

        @if ($errors->has('class_id'))
            <span class="help-block">
                <strong>{{ $errors->first('class_id') }}</strong>
            </span>
        @endif
    </div>
</div>

resources/views/library/books/index.blade.php
@extends('layouts.app')

@section('title', __('All Books'))

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2" id="side-navbar">
                @include('layouts.leftside-menubar')
            </div>
            <div class="col-md-10" id="main-container">
                <div class="panel panel-default">
                    <div class="page-panel-title">@lang('Books')</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        {{ $books->links() }}
                        <div class="table-responsive">
                            <table class="table table-bordered table-data-div table-hover">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>@lang('Title')</th>
                                        <th>@lang('Code')</th>
                                        <th>@lang('Author')</th>
                                        <th>@lang('Type')</th>
                                        <th>@lang('Quantity')</th>
                                        <th>@lang('Actions')</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($books as $book)
                                        <tr>
                                            <td>{{ ($loop->index + 1) }}</td>
                                            <td>{{ $book->title }}</td>
                                            <td>{{ $book->book_code }}</td>
                                            <td>{{ $book->author }}</td>
                                            <td>{{ $book->type }}</td>
                                            <td>{{ $book->quantity }}</td>
                                            <td>
                                                <div class="btn-group">
                                                    <a href="{{ route('library.books.show', $book->id) }}" class="btn btn-xs btn-info">
                                                        @lang('Details')
                                                    </a>
                                                </div>
                                                <div class="btn-group">
                                                    <a href="{{ route('library.books.edit', $book->id) }}" class="btn btn-xs btn-success">
                                                        @lang('Edit')
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        {{ $books->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection